//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA09Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BA09Bot.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter daily report..
        /// </summary>
        public static string Ask_DailyReport {
            get {
                return ResourceManager.GetString("Ask_DailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is detail?.
        /// </summary>
        public static string Ask_Description {
            get {
                return ResourceManager.GetString("Ask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When does it end?.
        /// </summary>
        public static string Ask_EndDate {
            get {
                return ResourceManager.GetString("Ask_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When does it start?.
        /// </summary>
        public static string Ask_StartDate {
            get {
                return ResourceManager.GetString("Ask_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is subject.
        /// </summary>
        public static string Ask_Subject {
            get {
                return ResourceManager.GetString("Ask_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Appointment.
        /// </summary>
        public static string Create_Appointment {
            get {
                return ResourceManager.GetString("Create_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a good evening!.
        /// </summary>
        public static string Created_DailyReport {
            get {
                return ResourceManager.GetString("Created_DailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Appointment.
        /// </summary>
        public static string Creating_Appointment {
            get {
                return ResourceManager.GetString("Creating_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} done..
        /// </summary>
        public static string Done_Operation {
            get {
                return ResourceManager.GetString("Done_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a product name.
        /// </summary>
        public static string Enter_ProductName {
            get {
                return ResourceManager.GetString("Enter_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get next task.
        /// </summary>
        public static string Get_NextTask {
            get {
                return ResourceManager.GetString("Get_NextTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all tasks.
        /// </summary>
        public static string Get_Tasks {
            get {
                return ResourceManager.GetString("Get_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to me by using following phrases:
        ///{0}
        ///I may also talk to you time to time..
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appointments today.
        /// </summary>
        public static string Menu_Appointment_For_Today {
            get {
                return ResourceManager.GetString("Menu_Appointment_For_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create appointment.
        /// </summary>
        public static string Menu_Create_Appointment {
            get {
                return ResourceManager.GetString("Menu_Create_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily report.
        /// </summary>
        public static string Menu_Daily_Report {
            get {
                return ResourceManager.GetString("Menu_Daily_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search product.
        /// </summary>
        public static string Menu_SearchProduct {
            get {
                return ResourceManager.GetString("Menu_SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task menu.
        /// </summary>
        public static string Menu_Task_Menu {
            get {
                return ResourceManager.GetString("Menu_Task_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select what you want to do..
        /// </summary>
        public static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointment today..
        /// </summary>
        public static string No_Appointment_Today {
            get {
                return ResourceManager.GetString("No_Appointment_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more appointment..
        /// </summary>
        public static string No_More_Appointment {
            get {
                return ResourceManager.GetString("No_More_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tasks.
        /// </summary>
        public static string No_Tasks {
            get {
                return ResourceManager.GetString("No_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a notification for you..
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string Open_In_Browser {
            get {
                return ResourceManager.GetString("Open_In_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to the default value..
        /// </summary>
        public static string Reset_To_Default {
            get {
                return ResourceManager.GetString("Reset_To_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than {0} items. Please retry the search..
        /// </summary>
        public static string Retry_More_Than_x_Items {
            get {
                return ResourceManager.GetString("Retry_More_Than_x_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click the item to see the detail..
        /// </summary>
        public static string Select_For_Detail {
            get {
                return ResourceManager.GetString("Select_For_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        public static string Select_Menu {
            get {
                return ResourceManager.GetString("Select_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select operation..
        /// </summary>
        public static string Select_Operation {
            get {
                return ResourceManager.GetString("Select_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click to sign in:.
        /// </summary>
        public static string SignIn_Prompt {
            get {
                return ResourceManager.GetString("SignIn_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
    }
}
