//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthBot.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost done! Please copy this number and paste it back to your chat so your authentication can complete:.
        /// </summary>
        internal static string Almost_Done {
            get {
                return ResourceManager.GetString("Almost_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Required.
        /// </summary>
        internal static string Auth_Required {
            get {
                return ResourceManager.GetString("Auth_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log you in at this time, please try again later.
        /// </summary>
        internal static string Could_Not_Signin {
            get {
                return ResourceManager.GetString("Could_Not_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry but I couldn&apos;t validate your number. Please try authenticating once again..
        /// </summary>
        internal static string Faile_To_Validate_Authcode {
            get {
                return ResourceManager.GetString("Faile_To_Validate_Authcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks {0}. You are now logged in..
        /// </summary>
        internal static string Loggedin {
            get {
                return ResourceManager.GetString("Loggedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste back the number you received in your authentication screen..
        /// </summary>
        internal static string Pasteback_Authcode {
            get {
                return ResourceManager.GetString("Pasteback_Authcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been signed out. You can now close this window..
        /// </summary>
        internal static string Signed_Out {
            get {
                return ResourceManager.GetString("Signed_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry but something went wrong while authenticating..
        /// </summary>
        internal static string Something_Went_Wrong_Auth {
            get {
                return ResourceManager.GetString("Something_Went_Wrong_Auth", resourceCulture);
            }
        }
    }
}
